#split panes using | and -
bind | split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'
unbind '"'
unbind %

# Enable mouse control
set -g mouse on

# Change window numbering 
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Customizing status bar
set -g status-bg "#b5222f"
set -g status-style fg="#fff9ed"
set -g status-right ""
set -g mode-keys vi
set -g status-keys vi
set -s escape-time 0

set-option -g focus-events on
set-option -sa terminal-features ',xterm-256color:RGB'
